[package]
edition = "2021"
name = "foo-fuzz"
publish = false
version = "0.0.0"

[package.metadata]
cargo-fuzz = true

[dependencies]
arbitrary = {version = "1", features = ["derive"]}
libfuzzer-sys = "0.4"
tokio = {version = "1", features = []}
s3s = "0.8.1"

[dependencies.foo]
path = ".."

[[bin]]
bench = false
doc = false
name = "fuzz_target_1"
path = "fuzz_targets/fuzz_target_1.rs"
test = false
